### ISSUE TITLE
not compatible with atom version 0.208.0

### ISSUE THREAD

**Issue by manV** [Glavin001/atom-playlist#29]

**Comment by mainiak** [comment]
Atom 1.0.0 seems not to be compatible as well.

**Comment by Glavin001** [comment]
This package is currently not maintained.

I actually like the idea of this package and may revisit it someday. For now, I'd recommend not installing it until you see a new release being published :wink:.

**Comment by shawninder** [comment]
@Glavin001 I suggest you add this at the top of README.md
